version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wutang
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  wutang-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: wutang-backend
    environment:
      FLASK_ENV: development
      POSTGRES_URL: postgresql://postgres:postgres@db:5432/wutang
    ports:
      - "5002:5002"
    volumes:
      - ./backend:/app
    depends_on:
      - db

volumes:
  postgres_data:
