
FROM python:3.13.0

RUN pip install poetry

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root

RUN mkdir -p /app/logs

EXPOSE 5002

CMD ["poetry", "run", "flask", "--debug", "run", "--host=0.0.0.0", "-p", "5002"]