name: Build and Push to ECR

on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        run: |
          # Replace these variables with your AWS ECR repository details
          IMAGE_NAME=wutang-backend
          AWS_REGION=us-east-2  # Update this to your desired region
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          # Define the full image URI
          IMAGE_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:latest"

          # Build the Docker image
          docker build -t ${IMAGE_NAME} ./backend

          # Tag the Docker image
          docker tag ${IMAGE_NAME} ${IMAGE_URI}

          # Push the Docker image to ECR
          docker push ${IMAGE_URI}

